services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: sep490_backend
    ports:
      - "7167:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - FRONTEND_BASE_URL=http://localhost:5124
    env_file:
      - ./Backend/.env
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: sep490_frontend
    ports:
      - "5124:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - BackendApiUrl=http://backend:8080/
      - Backend__BaseUrl=http://backend:8080/
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    restart: unless-stopped
